export type Metodologia = {
  id: string
  nombre: string
  emoji: string
  categoria: 'persuasion' | 'storytelling' | 'educacion' | 'conversion' | 'seo' | 'viralidad'
  descripcion: string
  estructura: string[]
  ejemplo: string
  nivelDificultad: 'básico' | 'intermedio' | 'avanzado'
  mejorPara: string
}

export const CATEGORIAS = {
  persuasion:   { label: 'Persuasión',   color: '#7c3aed' },
  storytelling: { label: 'Storytelling', color: '#f59e0b' },
  educacion:    { label: 'Educación',    color: '#06b6d4' },
  conversion:   { label: 'Conversión',   color: '#10b981' },
  seo:          { label: 'SEO',          color: '#ef4444' },
  viralidad:    { label: 'Viralidad',    color: '#ec4899' },
}

export const METODOLOGIAS: Metodologia[] = [
  // ── PERSUASIÓN ────────────────────────────────────────────────
  {
    id: 'pas',
    nombre: 'PAS',
    emoji: '🔥',
    categoria: 'persuasion',
    descripcion: 'Problema → Agitación → Solución. La fórmula clásica de copywriting aplicada a blogs.',
    estructura: ['1. El Problema (describe el dolor exacto del lector)', '2. Agitación (amplifica las consecuencias de no resolverlo)', '3. La Solución (tu método, producto o perspectiva)'],
    ejemplo: 'Artículo: "Por qué tu blog no genera ventas"',
    nivelDificultad: 'básico',
    mejorPara: 'Artículos de problema-solución, posts de ventas',
  },
  {
    id: 'aida',
    nombre: 'AIDA',
    emoji: '🎯',
    categoria: 'persuasion',
    descripcion: 'Atención → Interés → Deseo → Acción. La estructura publicitaria más probada del mundo.',
    estructura: ['1. Atención (gancho que detiene el scroll)', '2. Interés (datos, historia o contexto relevante)', '3. Deseo (beneficios, transformación posible)', '4. Acción (CTA claro y específico)'],
    ejemplo: 'Artículo: "El método que duplicó mi tráfico en 30 días"',
    nivelDificultad: 'básico',
    mejorPara: 'Posts orientados a conversión, landing pages de contenido',
  },
  {
    id: 'bab',
    nombre: 'Before-After-Bridge',
    emoji: '🌉',
    categoria: 'persuasion',
    descripcion: 'Muestra el mundo actual del lector, el mundo ideal, y tú eres el puente entre ambos.',
    estructura: ['1. Antes (la situación actual, el dolor)', '2. Después (la visión del éxito, la transformación)', '3. El Puente (cómo pasar de A a B: tu método)'],
    ejemplo: 'Artículo: "De 0 a 10,000 suscriptores en 6 meses"',
    nivelDificultad: 'básico',
    mejorPara: 'Casos de éxito, transformaciones, testimonios expandidos',
  },
  {
    id: '4us',
    nombre: 'Las 4 Us',
    emoji: '💎',
    categoria: 'persuasion',
    descripcion: 'Útil, Urgente, Único, Ultra-específico. Cada sección debe cumplir las 4 Us.',
    estructura: ['1. Útil (qué valor concreto obtiene el lector)', '2. Urgente (por qué importa ahora, no después)', '3. Único (qué lo diferencia de todo lo demás)', '4. Ultra-específico (datos, nombres, números reales)'],
    ejemplo: 'Artículo: "7 tácticas de SEO que funcionan solo en 2024"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts altamente orientados a resultados',
  },
  {
    id: 'fab',
    nombre: 'FAB',
    emoji: '⚡',
    categoria: 'persuasion',
    descripcion: 'Features → Advantages → Benefits. Transforma características en beneficios emocionales.',
    estructura: ['1. Característica (qué es exactamente)', '2. Ventaja (qué hace mejor que otras opciones)', '3. Beneficio (qué significa para la vida del lector)'],
    ejemplo: 'Artículo: "Por qué publicar semanalmente cambia todo"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Reviews, comparativas, posts de producto/metodología',
  },
  {
    id: 'slap',
    nombre: 'SLAP',
    emoji: '👋',
    categoria: 'persuasion',
    descripcion: 'Stop → Look → Act → Purchase. Secuencia de atención a conversión.',
    estructura: ['1. Stop (detén al lector con algo inesperado)', '2. Look (haz que se fije en el problema real)', '3. Act (dales el primer paso accionable)', '4. Purchase/CTA (invítalos a ir más lejos)'],
    ejemplo: 'Artículo: "Para de hacer esto en tu blog ahora mismo"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts de contenido + oferta, artículos de alto CTA',
  },
  {
    id: 'pppp',
    nombre: '4 Ps de Bryant',
    emoji: '🎭',
    categoria: 'persuasion',
    descripcion: 'Promise → Picture → Proof → Push. Promesa, visión, evidencia, empuje.',
    estructura: ['1. Promesa (el beneficio central que ofreces)', '2. Imagen (pinta el escenario de éxito vividamente)', '3. Prueba (datos, testimonios, casos reales)', '4. Empuje (CTA con urgencia o razón específica)'],
    ejemplo: 'Artículo: "Cómo escribir artículos que se comparten solos"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts de lanzamiento, artículos de alto ticket',
  },

  // ── STORYTELLING ──────────────────────────────────────────────
  {
    id: 'heroe',
    nombre: 'El Viaje del Héroe',
    emoji: '🦸',
    categoria: 'storytelling',
    descripcion: 'Tu lector es el héroe. Tú eres el mentor. Estructura de 3 actos adaptada a blogs.',
    estructura: ['1. El Mundo Ordinario (la situación actual del lector)', '2. El Llamado a la Aventura (el problema o desafío)', '3. Cruzar el Umbral (decidir cambiar)', '4. Pruebas y Aliados (el proceso, los obstáculos)', '5. La Resurrección (el punto de quiebre)','6. El Regreso con el Elixir (la transformación final)'],
    ejemplo: 'Artículo: "Mi historia de 3 años fracasando hasta encontrar mi voz"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts personales, casos de estudio largos, contenido de marca',
  },
  {
    id: 'star',
    nombre: 'STAR',
    emoji: '⭐',
    categoria: 'storytelling',
    descripcion: 'Situation → Task → Action → Result. La estructura de storytelling más usada en negocios.',
    estructura: ['1. Situación (contexto y escenario inicial)', '2. Tarea (el desafío o objetivo específico)', '3. Acción (qué hiciste exactamente, paso a paso)', '4. Resultado (el impacto medible que obtuviste)'],
    ejemplo: 'Artículo: "Cómo ayudé a un cliente a triplicar su tráfico"',
    nivelDificultad: 'básico',
    mejorPara: 'Casos de estudio, posts de resultados, testimonios',
  },
  {
    id: 'sparkline',
    nombre: 'Sparkline (Nancy Duarte)',
    emoji: '✨',
    categoria: 'storytelling',
    descripcion: 'Alterna entre "lo que es" y "lo que podría ser" para crear tensión narrativa.',
    estructura: ['1. Lo que ES (la realidad actual, los hechos)', '2. Lo que PODRÍA SER (la visión ideal)', '3. Lo que ES (obstáculos reales)', '4. Lo que PODRÍA SER (cuando se superen)', '5. El Nuevo Comienzo (llamado a actuar)'],
    ejemplo: 'Artículo: "La industria del blog está rota. Así podría ser diferente."',
    nivelDificultad: 'avanzado',
    mejorPara: 'Manifiestos, posts de opinión fuertes, artículos de visión',
  },
  {
    id: 'in_medias_res',
    nombre: 'In Medias Res',
    emoji: '🎬',
    categoria: 'storytelling',
    descripcion: 'Empieza en el medio de la acción, luego retrocede y avanza. Máxima intriga desde la primera línea.',
    estructura: ['1. Apertura en el clímax (empieza donde más tensión hay)', '2. Flash back: el origen (cómo llegaste ahí)', '3. El desarrollo (el camino recorrido)', '4. Regresa al presente (la resolución)', '5. Lección aprendida (el insight del lector)'],
    ejemplo: 'Artículo: "Ese día perdí todo mi tráfico. Lo que hice después cambió mi negocio."',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts personales con alta carga emocional',
  },
  {
    id: 'mini_historia',
    nombre: 'Mini-historia + Lección',
    emoji: '📚',
    categoria: 'storytelling',
    descripcion: 'Historia breve al inicio → insight aplicable. La fórmula de las fábulas modernizada.',
    estructura: ['1. La historia (breve, específica, con detalle sensorial)', '2. El giro (el momento de aprendizaje)', '3. La lección universal (qué significa para todos)', '4. La aplicación práctica (cómo usarlo hoy)'],
    ejemplo: 'Artículo: "Lo que un taxista me enseñó sobre marketing de contenidos"',
    nivelDificultad: 'básico',
    mejorPara: 'Posts reflexivos, LinkedIn/newsletter, contenido inspiracional',
  },
  {
    id: 'tres_actos',
    nombre: 'Tres Actos Clásicos',
    emoji: '🎭',
    categoria: 'storytelling',
    descripcion: 'Planteamiento → Nudo → Desenlace. La estructura más antigua y efectiva de la narrativa humana.',
    estructura: ['Acto I — Planteamiento (presenta el contexto y el conflicto central)', 'Acto II — Nudo (el desarrollo, las complicaciones, el proceso)', 'Acto III — Desenlace (la resolución, la transformación, el insight final)'],
    ejemplo: 'Artículo: "3 años, 200 artículos, 1 lección que cambió todo"',
    nivelDificultad: 'básico',
    mejorPara: 'Cualquier artículo narrativo, posts personales',
  },

  // ── EDUCACIÓN ─────────────────────────────────────────────────
  {
    id: 'tutorial',
    nombre: 'Tutorial Paso a Paso',
    emoji: '🪜',
    categoria: 'educacion',
    descripcion: 'Guía secuencial y práctica. El lector puede replicar exactamente lo que describes.',
    estructura: ['Introducción (qué aprenderás y por qué importa)', 'Prerrequisitos (qué necesitas antes de empezar)', 'Paso 1: [Acción específica]', 'Paso 2: [Acción específica]', 'Paso 3: [Acción específica]', 'Errores comunes a evitar', 'Resultado final esperado'],
    ejemplo: 'Artículo: "Cómo configurar tu blog en WordPress en 30 minutos"',
    nivelDificultad: 'básico',
    mejorPara: 'Guías técnicas, how-tos, contenido paso a paso',
  },
  {
    id: 'frameworks',
    nombre: 'Explicación de Framework',
    emoji: '🏗️',
    categoria: 'educacion',
    descripcion: 'Presenta un modelo mental o sistema de forma estructurada y memorable.',
    estructura: ['1. El problema que resuelve el framework', '2. Presentación del modelo (con nombre y acrónimo si aplica)', '3. Cada componente explicado con ejemplos', '4. Cómo usar el framework en la práctica', '5. Errores frecuentes al aplicarlo', '6. Ejemplo completo de aplicación'],
    ejemplo: 'Artículo: "El Framework ACES para crear contenido que convierte"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts de metodología, contenido de thought leadership',
  },
  {
    id: 'comparativa',
    nombre: 'Post Comparativo',
    emoji: '⚖️',
    categoria: 'educacion',
    descripcion: 'Compara opciones, herramientas o enfoques de forma objetiva para ayudar al lector a decidir.',
    estructura: ['Introducción (por qué importa esta comparación)', 'Criterios de evaluación (en qué te basas)', 'Opción A: pros, contras, mejor para quién', 'Opción B: pros, contras, mejor para quién', 'Tabla comparativa', 'Recomendación final según perfil del lector'],
    ejemplo: 'Artículo: "WordPress vs Webflow: cuál elegir según tu negocio"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Reviews, comparativas de herramientas, SEO de intención comercial',
  },
  {
    id: 'guia_definitiva',
    nombre: 'La Guía Definitiva',
    emoji: '📕',
    categoria: 'educacion',
    descripcion: 'El recurso más completo del internet sobre un tema. Diseñado para posicionarse en SEO a largo plazo.',
    estructura: ['Introducción y alcance del artículo', 'Fundamentos (qué es, por qué importa)', 'Historia y evolución del tema', 'Conceptos clave y glosario', 'Guía práctica completa', 'Herramientas recomendadas', 'Casos de estudio reales', 'Errores más comunes', 'Preguntas frecuentes', 'Recursos adicionales'],
    ejemplo: 'Artículo: "La Guía Definitiva de Email Marketing para Bloggers"',
    nivelDificultad: 'avanzado',
    mejorPara: 'SEO long-form, pillar pages, contenido de autoridad',
  },
  {
    id: 'mito_realidad',
    nombre: 'Mitos vs Realidad',
    emoji: '🔍',
    categoria: 'educacion',
    descripcion: 'Desmonta creencias erróneas populares con datos y evidencia. Posiciona al autor como experto crítico.',
    estructura: ['Introducción (por qué existen tantos mitos sobre este tema)', 'Mito #1: [afirmación falsa] → La Realidad: [la verdad con evidencia]', 'Mito #2: [afirmación falsa] → La Realidad:', 'Mito #3: [afirmación falsa] → La Realidad:', '(continúa para cada mito)', 'Conclusión: cómo pensar correctamente sobre el tema'],
    ejemplo: 'Artículo: "7 mitos sobre el SEO que siguen costándote tráfico"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Contenido de autoridad, posts de debate, temas con mucha desinformación',
  },
  {
    id: 'recursos',
    nombre: 'Post de Recursos',
    emoji: '🗂️',
    categoria: 'educacion',
    descripcion: 'Compila las mejores herramientas, libros, recursos o referencias sobre un tema.',
    estructura: ['Por qué compilé esta lista (contexto y criterios)', 'Categoría 1: [Tipo de recurso] — 3-5 recursos con descripción breve', 'Categoría 2: [Tipo de recurso]', 'Categoría 3: [Tipo de recurso]', 'Mis favoritos personales (selección curada)', 'Cómo sacarle el máximo provecho a cada uno'],
    ejemplo: 'Artículo: "30 herramientas gratuitas para bloggers en 2024"',
    nivelDificultad: 'básico',
    mejorPara: 'Posts de valor rápido, SEO por intención informacional, listas de herramientas',
  },
  {
    id: 'pregunta_respuesta',
    nombre: 'Pregunta → Respuesta Profunda',
    emoji: '❓',
    categoria: 'educacion',
    descripcion: 'Una pregunta que tiene tu audiencia, respondida de forma exhaustiva. SEO por intención.',
    estructura: ['La pregunta completa y por qué importa', 'Respuesta directa en 2-3 oraciones (para Google)', 'Contexto y antecedentes', 'La respuesta completa desarrollada', 'Excepciones y casos especiales', 'Preguntas relacionadas que deberías hacerte'],
    ejemplo: 'Artículo: "¿Cuántos artículos al mes necesito para posicionar mi blog?"',
    nivelDificultad: 'básico',
    mejorPara: 'SEO FAQ, snippets de Google, contenido de soporte',
  },
  {
    id: 'caso_estudio',
    nombre: 'Caso de Estudio',
    emoji: '🔬',
    categoria: 'educacion',
    descripcion: 'Análisis profundo de un resultado real, propio o de un cliente. El contenido más creíble.',
    estructura: ['Resumen ejecutivo (el resultado en 3 líneas)', 'El punto de partida (situación inicial, métricas base)', 'El problema específico a resolver', 'La estrategia y método aplicado', 'Resultados por etapa', 'Métricas finales vs métricas iniciales', 'Lecciones aprendidas y reproducibles'],
    ejemplo: 'Artículo: "Cómo pasé de 500 a 15,000 visitas en 4 meses (con pruebas)"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Contenido de autoridad, generación de leads, ventas de servicios',
  },
  {
    id: 'reportaje',
    nombre: 'Reportaje / Investigación',
    emoji: '📰',
    categoria: 'educacion',
    descripcion: 'Artículo con datos originales, encuestas o investigación propia. Altamente compartible.',
    estructura: ['El hallazgo principal (el dato más sorprendente primero)', 'Metodología de la investigación', 'Datos y análisis por sección', 'Gráficos y visualizaciones', 'Implicaciones para el lector', 'Conclusiones y predicciones'],
    ejemplo: 'Artículo: "Encuestamos a 500 bloggers: esto es lo que realmente funciona"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Linkbuilding, viralidad en redes, posicionamiento como referente',
  },

  // ── CONVERSIÓN ────────────────────────────────────────────────
  {
    id: 'so_what',
    nombre: 'So What? Framework',
    emoji: '🤷',
    categoria: 'conversion',
    descripcion: 'Responde "¿y a mí qué?" en cada párrafo. Hace el contenido brutalmente relevante.',
    estructura: ['Afirmación 1 → ¿Y a ti qué? → Implicación directa para el lector', 'Afirmación 2 → ¿Y a ti qué? → Implicación directa', 'Afirmación 3 → ¿Y a ti qué? → Implicación directa', 'La acción específica que deberías tomar hoy'],
    ejemplo: 'Artículo: "El algoritmo de LinkedIn cambió. ¿Y a ti qué?"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts de news y tendencias, contenido de noticias del sector',
  },
  {
    id: 'objecion',
    nombre: 'Destructor de Objeciones',
    emoji: '🛡️',
    categoria: 'conversion',
    descripcion: 'Anticipa cada objeción del lector y la neutraliza antes de que aparezca.',
    estructura: ['Presentación del tema y su beneficio principal', 'Objeción #1: "Pero [resistencia]..." → Respuesta:', 'Objeción #2: "No tengo [recurso]..." → Respuesta:', 'Objeción #3: "Eso no funciona para [mi caso]..." → Respuesta:', 'La propuesta final, ya sin resistencias'],
    ejemplo: 'Artículo: "Por qué deberías cobrar más (y cómo silenciar al impostor)"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts de venta soft, conversión de lectores a clientes',
  },
  {
    id: 'urgencia',
    nombre: 'El Costo de la Inacción',
    emoji: '⏰',
    categoria: 'conversion',
    descripcion: 'Hace visible el precio de no actuar ahora. Convierte el "lo haré después" en urgencia real.',
    estructura: ['La situación actual (dónde está el lector hoy)', 'Qué pasa si nada cambia en 6 meses', 'Qué pasa si nada cambia en 1 año', 'El costo acumulado (emocional, financiero, de oportunidad)', 'El contraste: qué PODRÍA pasar si actúa hoy', 'El primer paso (pequeño y accionable)'],
    ejemplo: 'Artículo: "¿Cuánto te está costando no tener un blog ahora mismo?"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts de conversión directa, emails, artículos de oferta',
  },
  {
    id: 'prueba_social',
    nombre: 'Estructura de Prueba Social',
    emoji: '👥',
    categoria: 'conversion',
    descripcion: 'Construye credibilidad a través de datos, ejemplos y evidencia verificable.',
    estructura: ['El argumento central que quieres validar', 'Evidencia #1: Dato estadístico + fuente', 'Evidencia #2: Caso real nombrado', 'Evidencia #3: Experiencia propia con métricas', 'Lo que todos estos ejemplos tienen en común', 'Por qué tú puedes replicarlo'],
    ejemplo: 'Artículo: "Por qué el contenido largo posiciona mejor (con 12 estudios)"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts de credibilidad, artículos de conversión, SEO de autoridad',
  },
  {
    id: 'lista_pro',
    nombre: 'Listicle Profundo',
    emoji: '📋',
    categoria: 'conversion',
    descripcion: 'Lista numerada donde cada punto tiene profundidad real, no solo bullets superficiales.',
    estructura: ['Intro: por qué esta lista y cómo usarla', 'Punto 1: [Título] → explicación + ejemplo + por qué funciona', 'Punto 2: [Título] → explicación + ejemplo + por qué funciona', '(...repetir para cada punto...)', 'Punto N: [Título]', 'El patrón que conecta todos los puntos', 'Cuál empezar primero'],
    ejemplo: 'Artículo: "21 tipos de contenido que tu audiencia quiere ver (y tú no publicas)"',
    nivelDificultad: 'básico',
    mejorPara: 'Contenido para principiantes, SEO, posts de alto alcance en redes',
  },
  {
    id: 'micro_compromiso',
    nombre: 'Micro-Compromisos',
    emoji: '✅',
    categoria: 'conversion',
    descripcion: 'Lleva al lector de acuerdo en acuerdo hasta el CTA final. Cada "sí" pequeño facilita el grande.',
    estructura: ['Afirmación con la que todos están de acuerdo', 'Segunda afirmación (levemente más comprometida)', 'Tercera afirmación (ya implica un cambio)', 'La implicación lógica de las tres', 'El paso natural que surge de aceptar todo lo anterior'],
    ejemplo: 'Artículo: "Si ya sabes que necesitas un blog, ¿por qué no tienes uno todavía?"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Posts de conversión directa, artículos de cierre',
  },

  // ── SEO ───────────────────────────────────────────────────────
  {
    id: 'seo_clasico',
    nombre: 'SEO Clásico',
    emoji: '🔎',
    categoria: 'seo',
    descripcion: 'Estructura optimizada para posicionar en Google con intención de búsqueda informacional.',
    estructura: ['H1: Keyword principal + beneficio', 'Introducción con keyword en primeras 100 palabras', 'H2: Qué es / Definición del tema', 'H2: Por qué importa / Beneficios', 'H2: Cómo [hacer algo] — sección más larga', 'H2: Errores comunes', 'H2: Herramientas / Recursos', 'H2: Preguntas frecuentes (schema FAQ)', 'Conclusión con CTA'],
    ejemplo: 'Artículo: "Qué es el marketing de contenidos (y cómo usarlo en 2024)"',
    nivelDificultad: 'básico',
    mejorPara: 'Keywords informacionales, artículos de top-of-funnel',
  },
  {
    id: 'hub_spoke',
    nombre: 'Hub & Spoke (Pilar)',
    emoji: '🕸️',
    categoria: 'seo',
    descripcion: 'Artículo pilar que enlaza con artículos satélite. Construye autoridad topical.',
    estructura: ['Introducción amplia del tema (el hub)', 'Sección 1: Subtema A (enlaza a artículo satélite 1)', 'Sección 2: Subtema B (enlaza a artículo satélite 2)', 'Sección 3: Subtema C (enlaza a artículo satélite 3)', 'Sección 4: Subtema D (enlaza a artículo satélite 4)', 'Sección 5: Subtema E (enlaza a artículo satélite 5)', 'Conclusión que unifica todo el cluster'],
    ejemplo: 'Artículo: "Marketing de contenidos: la guía completa [Índice]"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Estrategia SEO de clusters temáticos, blogs de autoridad',
  },
  {
    id: 'skyscraper',
    nombre: 'Skyscraper',
    emoji: '🏙️',
    categoria: 'seo',
    descripcion: 'Toma el mejor artículo del top 1 de Google sobre un tema y hazlo 10x mejor.',
    estructura: ['Todo lo que el artículo #1 tiene, más:', 'Datos más actualizados', 'Más profundidad en cada sección', 'Casos reales adicionales', 'Una sección única que nadie más tiene', 'Mejor diseño y legibilidad', 'Recursos descargables o interactivos'],
    ejemplo: 'Artículo: "La guía más completa de email marketing de 2024"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Keywords competitivas, linkbuilding, ganar a artículos establecidos',
  },
  {
    id: 'featured_snippet',
    nombre: 'Optimizado para Featured Snippet',
    emoji: '📌',
    categoria: 'seo',
    descripcion: 'Estructura diseñada para aparecer en el cuadro destacado de Google (posición 0).',
    estructura: ['H1 con la keyword exacta como pregunta', 'Respuesta directa en 40-60 palabras justo después del H1', 'Definición concisa en 1-2 oraciones', 'Lista o tabla de los puntos principales', 'Desarrollo completo de cada punto', 'Preguntas relacionadas con respuestas cortas'],
    ejemplo: 'Artículo: "¿Cuántas palabras debe tener un artículo de blog?"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Keywords de pregunta, contenido definitorio, How-to',
  },
  {
    id: 'long_tail',
    nombre: 'Clúster de Long Tail',
    emoji: '🎣',
    categoria: 'seo',
    descripcion: 'Artículo que responde múltiples variaciones de una keyword long-tail en un solo post.',
    estructura: ['Keyword principal + definición', 'Variante 1: [keyword larga] → respuesta', 'Variante 2: [keyword larga] → respuesta', 'Variante 3: [keyword larga] → respuesta', 'Variante 4: [keyword larga] → respuesta', 'La guía práctica que une todas las variantes'],
    ejemplo: 'Artículo: "Cómo escribir un blog: para principiantes, gratis, sin experiencia"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Nichos con muchas búsquedas long-tail, tráfico orgánico rápido',
  },
  {
    id: 'actualizacion',
    nombre: 'Artículo de Actualización',
    emoji: '🔄',
    categoria: 'seo',
    descripcion: 'Actualiza un artículo antiguo con datos nuevos. Señal de frescura para Google.',
    estructura: ['Nota de actualización (fecha y qué cambió)', 'Resumen ejecutivo de los cambios principales', 'Sección original con datos actualizados', 'Nueva sección con información 2024', 'Qué ya no funciona (honestidad con el lector)', 'Qué funciona ahora mismo'],
    ejemplo: 'Artículo: "SEO en 2024: todo lo que cambió desde mi guía de 2022"',
    nivelDificultad: 'básico',
    mejorPara: 'Artículos propios que perdieron ranking, contenido evergreen',
  },

  // ── VIRALIDAD ─────────────────────────────────────────────────
  {
    id: 'opinion_fuerte',
    nombre: 'Opinión Fuerte / Hot Take',
    emoji: '🌶️',
    categoria: 'viralidad',
    descripcion: 'Toma una posición polarizante sobre un tema. Genera debate, shares y comentarios.',
    estructura: ['La afirmación provocadora (el hot take en 1 línea)', 'Por qué la mayoría lo hace mal (el contexto)', 'Tu argumento principal con evidencia', 'Las objeciones que anticipas + respuesta', 'Lo que cambiaría si el sector adoptara tu visión', 'Tu posición final, sin ceder'],
    ejemplo: 'Artículo: "El SEO está muerto. Y los que viven de él lo saben."',
    nivelDificultad: 'avanzado',
    mejorPara: 'LinkedIn, Twitter, newsletters con audiencia consolidada',
  },
  {
    id: 'contrariotarian',
    nombre: 'El Contrarian',
    emoji: '↩️',
    categoria: 'viralidad',
    descripcion: 'Contradice el consejo convencional con argumentos sólidos. Altamente compartible.',
    estructura: ['El consejo popular que vas a contradecir', 'Por qué todo el mundo lo sigue (y tiene sentido)', 'Los datos o experiencias que lo contradicen', 'La perspectiva alternativa que propones', 'En qué contextos SÍ funciona el consejo original', 'La conclusión matizada (no "siempre" ni "nunca")'],
    ejemplo: 'Artículo: "Publica menos, no más: el consejo que nadie quiere escuchar"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Audiencias avanzadas, nichos saturados, diferenciación de voz',
  },
  {
    id: 'prediccion',
    nombre: 'Predicciones y Tendencias',
    emoji: '🔮',
    categoria: 'viralidad',
    descripcion: 'Predice el futuro de tu industria con argumentación sólida. Altísima compartibilidad.',
    estructura: ['El estado actual de la industria', 'Las señales que ya están ocurriendo', 'Predicción #1: [lo que cambiará] + por qué', 'Predicción #2: [lo que desaparecerá] + por qué', 'Predicción #3: [lo que explotará] + por qué', 'Cómo prepararte para lo que viene', 'La apuesta: qué pasa si me equivoco'],
    ejemplo: 'Artículo: "El futuro del blogging en 2025: 5 predicciones que nadie más hace"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Inicio de año, eventos del sector, momentos de disrupcón',
  },
  {
    id: 'experimento',
    nombre: 'El Experimento',
    emoji: '🧪',
    categoria: 'viralidad',
    descripcion: 'Documenta un experimento que hiciste: hipótesis, proceso, resultados reales.',
    estructura: ['La hipótesis (qué querías probar y por qué)', 'Las reglas del experimento (cómo lo hiciste)', 'Lo que esperabas que pasara', 'Lo que realmente pasó (con datos reales)', 'El análisis: por qué pasó lo que pasó', 'Qué repetirías y qué cambiarías', 'Lo que tú puedes replicar'],
    ejemplo: 'Artículo: "Publiqué 30 días seguidos en LinkedIn: aquí están los resultados"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts con datos propios, contenido original, alta credibilidad',
  },
  {
    id: 'carta_abierta',
    nombre: 'Carta Abierta',
    emoji: '✉️',
    categoria: 'viralidad',
    descripcion: 'Dirigida a un grupo específico: "Una carta abierta a los bloggers que abandonan".',
    estructura: ['Querido/a [audiencia específica]:', 'Lo que he observado en ti (con empatía)', 'Lo que nadie te ha dicho todavía', 'Lo que en realidad necesitas saber', 'Lo que haría en tu lugar', 'Con respeto y honestidad, [tu nombre]'],
    ejemplo: 'Artículo: "Una carta abierta a los freelancers que se rinden en el primer año"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Alta viralidad emocional, comunidades específicas, newsletters',
  },
  {
    id: 'curated',
    nombre: 'Best Of / Curated Roundup',
    emoji: '🏆',
    categoria: 'viralidad',
    descripcion: 'Recopila lo mejor del año, del mes o del tema. Alta compartibilidad y backlinking.',
    estructura: ['Contexto: por qué esta selección ahora', 'Criterios de selección (tu perspectiva editorial)', '#1: [El mejor X] + por qué lo elegí', '#2: [El mejor X] + por qué lo elegí', '(...)', 'El patrón que conecta a todos los elegidos', 'Tu predicción para el próximo período'],
    ejemplo: 'Artículo: "Los 10 artículos de marketing que más me impactaron en 2024"',
    nivelDificultad: 'básico',
    mejorPara: 'Fin de año, celebraciones del sector, contenido de curaduría',
  },
  {
    id: 'entrevista',
    nombre: 'Post de Entrevista',
    emoji: '🎤',
    categoria: 'viralidad',
    descripcion: 'Entrevista a un experto y convierte sus respuestas en un artículo de blog de alto valor.',
    estructura: ['Introducción: quién es el entrevistado y por qué importa', 'Contexto y credenciales del experto', 'Pregunta 1 (la más impactante primero)', 'Pregunta 2', 'Pregunta 3', '(...)', 'Los 3 insights más importantes de la entrevista', 'Recursos del entrevistado para seguir aprendiendo'],
    ejemplo: 'Artículo: "Entrevisté al blogger con 1M de visitas: esto fue lo más sorprendente"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Networking, autoridad por asociación, alta compartibilidad',
  },
  {
    id: 'what_i_learned',
    nombre: '"Lo que aprendí de..."',
    emoji: '🎓',
    categoria: 'viralidad',
    descripcion: 'Extrae lecciones inesperadas de experiencias, libros, personas o eventos.',
    estructura: ['La fuente de aprendizaje (el libro, evento o experiencia)', 'Por qué esperabas algo diferente (el contraste)', 'Lección #1 + aplicación concreta', 'Lección #2 + aplicación concreta', 'Lección #3 + aplicación concreta', 'La lección más contraintuitiva de todas', 'Qué cambiarías en tu vida o trabajo a partir de hoy'],
    ejemplo: 'Artículo: "Lo que aprendí de publicar un artículo viral (que no fue lo que esperaba)"',
    nivelDificultad: 'básico',
    mejorPara: 'Posts personales, LinkedIn, newsletters, alta conexión emocional',
  },
  {
    id: 'confesion',
    nombre: 'La Confesión',
    emoji: '🙈',
    categoria: 'viralidad',
    descripcion: 'Revela errores, fracasos o verdades incómodas. La honestidad radical genera conexión masiva.',
    estructura: ['La verdad que has estado evitando decir', 'El contexto: por qué tardaste en admitirlo', 'Lo que pasó cuando lo ignoraste', 'El momento en que no pudiste seguir ignorándolo', 'Lo que cambió cuando lo aceptaste', 'Lo que quieres que el lector haga con esta información'],
    ejemplo: 'Artículo: "Cobré de menos 3 años por miedo. Esto es cuánto me costó."',
    nivelDificultad: 'intermedio',
    mejorPara: 'Construir comunidad, diferenciación de voz, audiencias que buscan autenticidad',
  },
  {
    id: 'manifiesto',
    nombre: 'Manifiesto',
    emoji: '📣',
    categoria: 'viralidad',
    descripcion: 'Declaración de principios sobre cómo debería hacerse algo. Llama a tu tribu.',
    estructura: ['Creemos que... (la declaración central)', 'El estado actual (lo que está roto o mal)', 'Principio #1: [Lo que defendemos]', 'Principio #2: [Lo que rechazamos]', 'Principio #3: [Lo que construimos]', 'A quién va dirigido este manifiesto', 'El llamado a unirse'],
    ejemplo: 'Artículo: "Manifiesto del blogging honesto: ya basta de contenido vacío"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Construcción de comunidad, diferenciación de marca, artículo fundacional',
  },
  {
    id: 'detras_escena',
    nombre: 'Detrás de Escena',
    emoji: '🎥',
    categoria: 'viralidad',
    descripcion: 'Muestra el proceso real, los números reales, la realidad sin filtros.',
    estructura: ['Qué vas a mostrar y por qué eres transparente', 'Los números reales (ingresos, tráfico, errores)', 'El proceso real (incluyendo lo feo)', 'Los momentos de duda y cómo los resolviste', 'Qué está funcionando actualmente', 'Qué no funciona y por qué lo sigues haciendo'],
    ejemplo: 'Artículo: "Detrás de mi artículo más viral: el proceso real, paso a paso"',
    nivelDificultad: 'básico',
    mejorPara: 'Construir confianza, audiencias que quieren aprender el proceso',
  },
  {
    id: 'numero_x',
    nombre: '[Número] + Beneficio + Tiempo',
    emoji: '🔢',
    categoria: 'viralidad',
    descripcion: 'La fórmula de título más clicada del internet. Número específico + beneficio + horizonte temporal.',
    estructura: ['Intro: por qué exactamente [número] y no otro', 'Tip #1 → explicación breve + ejemplo real', 'Tip #2 → explicación breve + ejemplo real', 'Tip #3 → explicación breve + ejemplo real', '(...hasta el número prometido...)', 'El tip más impactante de todos (el último)', '¿Por cuál empezar? (guía de priorización)'],
    ejemplo: 'Artículo: "5 estrategias de blog que dan resultados en menos de 90 días"',
    nivelDificultad: 'básico',
    mejorPara: 'Redes sociales, email, contenido de alto CTR',
  },
  {
    id: 'scqa',
    nombre: 'SCQA (McKinsey)',
    emoji: '💼',
    categoria: 'educacion',
    descripcion: 'Situation → Complication → Question → Answer. La estructura de comunicación ejecutiva.',
    estructura: ['Situación (el contexto que todos conocemos)', 'Complicación (algo que perturbó el equilibrio)', 'Pregunta (la duda natural que surge)', 'Respuesta (tu solución o perspectiva)'],
    ejemplo: 'Artículo: "Las reglas del blogging cambiaron en 2024. Aquí está el nuevo mapa."',
    nivelDificultad: 'avanzado',
    mejorPara: 'Audiencias profesionales, B2B, contenido de negocios',
  },
  {
    id: 'peel',
    nombre: 'PEEL',
    emoji: '🍊',
    categoria: 'educacion',
    descripcion: 'Point → Evidence → Explanation → Link. Estructura académica adaptada a blogs.',
    estructura: ['Point (el punto que vas a demostrar)', 'Evidence (evidencia que lo apoya: dato, ejemplo, historia)', 'Explanation (por qué esa evidencia apoya tu punto)', 'Link (cómo conecta con el siguiente punto o con la tesis central)'],
    ejemplo: 'Artículo: "Por qué el contenido largo domina el SEO (con 5 argumentos probados)"',
    nivelDificultad: 'intermedio',
    mejorPara: 'Artículos de argumento, contenido académico adaptado',
  },
  {
    id: 'hero_hub_help',
    nombre: 'Hero-Hub-Help',
    emoji: '🌟',
    categoria: 'conversion',
    descripcion: 'Tres tipos de contenido: Hero (viral), Hub (recurrente), Help (SEO). Un artículo puede ser los tres.',
    estructura: ['Apertura Hero: el gancho viral, el dato sorprendente', 'Sección Hub: el valor recurrente, la razón de volver', 'Sección Help: la guía práctica que posiciona en Google', 'CTA diferenciado para cada tipo de lector'],
    ejemplo: 'Artículo: "El artículo que resume todo lo que sé sobre crear contenido"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Artículos fundacionales, cornerstone content, posts de referencia',
  },
  {
    id: 'cuestion_solucion',
    nombre: 'Pregunta Incómoda → Solución Valiente',
    emoji: '💡',
    categoria: 'conversion',
    descripcion: 'Hace la pregunta que todos evitan y da una respuesta honesta.',
    estructura: ['La pregunta incómoda (que el lector tiene pero nadie hace)', 'Por qué es una pregunta que se evita', 'La respuesta honesta aunque no guste', 'Los matices que la hacen más verdadera', 'Qué hacer con esta verdad incómoda'],
    ejemplo: 'Artículo: "¿Vale la pena un blog en 2024? La respuesta honesta."',
    nivelDificultad: 'intermedio',
    mejorPara: 'Posts de diferenciación, audiencias maduras, builds de confianza',
  },
  {
    id: 'micro_contenido',
    nombre: 'Post Micro-Formato',
    emoji: '⚡',
    categoria: 'viralidad',
    descripcion: 'Artículo breve de 300-500 palabras diseñado para ser leído completo. Alta tasa de finalización.',
    estructura: ['La idea central en 1 párrafo (el núcleo)', 'El argumento en 2-3 párrafos', 'Un ejemplo concreto y específico', 'La conclusión en 1 frase memorable'],
    ejemplo: 'Artículo: "La única métrica que importa en tu blog"',
    nivelDificultad: 'básico',
    mejorPara: 'Email, audiencias ocupadas, ideas que no necesitan más desarrollo',
  },
  {
    id: 'abc',
    nombre: 'El ABC del Tema',
    emoji: '🔤',
    categoria: 'educacion',
    descripcion: 'Glosario narrativo del tema: cada concepto clave explicado en orden accesible.',
    estructura: ['Por qué necesitas entender estos términos', 'Concepto A: [término fundamental]', 'Concepto B: [término fundamental]', 'Concepto C: [término fundamental]', '(...continúa por todos los términos clave...)', 'Cómo encajan todos estos conceptos en la práctica'],
    ejemplo: 'Artículo: "El ABC del SEO: 15 términos que necesitas entender hoy"',
    nivelDificultad: 'básico',
    mejorPara: 'Audiencias principiantes, contenido de onboarding, SEO definitorio',
  },
  {
    id: 'round_expert',
    nombre: 'Roundup de Expertos',
    emoji: '👨‍👩‍👧‍👦',
    categoria: 'viralidad',
    descripcion: 'Recoge la opinión de múltiples expertos sobre una sola pregunta. Virabilidad garantizada.',
    estructura: ['La pregunta central que hiciste a los expertos', 'Por qué elegiste a estos expertos', 'Respuesta del experto #1 + su contexto', 'Respuesta del experto #2 + su contexto', '(...)', 'Los patrones que aparecen en todas las respuestas', 'Tu propia conclusión editorial'],
    ejemplo: 'Artículo: "Pregunté a 20 bloggers exitosos: ¿Cuál es su mayor error?"',
    nivelDificultad: 'avanzado',
    mejorPara: 'Linkbuilding natural, construcción de red, viralidad por menciones',
  },
]
