export type Technique = {
  id: string
  name: string
  category: string
  origin: string
  emoji: string
  description: string
  howTo: string
  example: string
  bestFor: string[]
  power: 'alta' | 'muy alta' | 'legendaria'
}

export const CATEGORIES = [
  { id: 'todos',        label: 'Todas',               emoji: '⚡' },
  { id: 'formulas',     label: 'Fórmulas Clásicas',   emoji: '📐' },
  { id: 'storytelling', label: 'Storytelling',         emoji: '📖' },
  { id: 'titulos',      label: 'Titulares',            emoji: '🎯' },
  { id: 'persuasion',   label: 'Persuasión',           emoji: '🧠' },
  { id: 'emocional',    label: 'Gatillos Emocionales', emoji: '❤️' },
  { id: 'estructura',   label: 'Estructura',           emoji: '🏛️' },
  { id: 'engagement',   label: 'Engagement',           emoji: '🔥' },
]

export const TECHNIQUES: Technique[] = [
  // ────────────────── FÓRMULAS CLÁSICAS ──────────────────
  {
    id: 'aida',
    name: 'AIDA',
    category: 'formulas',
    origin: 'Elias St. Elmo Lewis, 1898',
    emoji: '🎯',
    description: 'La fórmula madre del copywriting. Atención → Interés → Deseo → Acción. Usada por las marcas más grandes del mundo durante más de 120 años.',
    howTo: '1. ATENCIÓN: Abre con algo que detenga al lector (estadística, pregunta, afirmación audaz). 2. INTERÉS: Presenta el problema o la oportunidad con detalle. 3. DESEO: Muestra la transformación, el beneficio, el "después". 4. ACCIÓN: Un CTA claro y específico.',
    example: '**A:** "El 87% de los blogs mueren en 6 meses. El tuyo no tiene por qué." **I:** Descubre por qué el contenido genérico ya no funciona en 2024. **D:** Imagina publicar 1 artículo y ver 50.000 lectores en 30 días. **A:** Descarga la guía gratuita ahora.',
    bestFor: ['artículos de ventas', 'intros de blog', 'emails', 'CTAs'],
    power: 'legendaria',
  },
  {
    id: 'pas',
    name: 'PAS',
    category: 'formulas',
    origin: 'Dan Kennedy',
    emoji: '🔥',
    description: 'Problema → Agitación → Solución. La fórmula más poderosa para conectar con lectores que sufren un problema real. Duele antes de curar.',
    howTo: '1. PROBLEMA: Nómbralo con precisión quirúrgica. 2. AGITACIÓN: Profundiza en el dolor — consecuencias, emociones, futuro oscuro si no actúan. 3. SOLUCIÓN: Presenta tu respuesta como el alivio exacto.',
    example: '**P:** Tu blog lleva 6 meses publicando y aún tienes 0 suscriptores. **A:** Cada semana sin tráfico es dinero que no entra, credibilidad que no construyes y audiencia que se va con tu competencia. **S:** El Sistema BlogOS cambia eso en 30 días.',
    bestFor: ['artículos de conversión', 'emails fríos', 'páginas de venta'],
    power: 'legendaria',
  },
  {
    id: 'bab',
    name: 'BAB (Before-After-Bridge)',
    category: 'formulas',
    origin: 'Copywriting tradicional',
    emoji: '🌉',
    description: 'Antes → Después → Puente. Muestra el contraste entre la realidad actual del lector y su vida ideal, luego ofrece el camino.',
    howTo: '1. BEFORE: Pinta la situación actual con detalle. 2. AFTER: Describe vívidamente el futuro deseado. 3. BRIDGE: Presenta tu método/producto como el puente entre ambos.',
    example: '**Antes:** Publicas cada semana sin ver resultados. **Después:** Imagina despertar con 500 nuevos suscriptores y 3 clientes potenciales en tu bandeja. **Puente:** La metodología de Topic Clusters de BlogOS hace exactamente eso.',
    bestFor: ['testimoniales', 'páginas de ventas', 'intros de artículo'],
    power: 'muy alta',
  },
  {
    id: 'fab',
    name: 'FAB (Features-Advantages-Benefits)',
    category: 'formulas',
    origin: 'Marketing industrial',
    emoji: '✨',
    description: 'Características → Ventajas → Beneficios. Transforma características técnicas en beneficios emocionales que el lector realmente desea.',
    howTo: 'Por cada característica, pregunta "¿Y qué?" dos veces. La respuesta final es el beneficio real que debes comunicar.',
    example: '**F:** Publicamos 3 veces por semana. **A:** Más contenido indexado por Google. **B:** Más tráfico orgánico gratuito y más clientes potenciales que llegan solos a ti.',
    bestFor: ['descripciones de productos', 'artículos comparativos', 'listas de beneficios'],
    power: 'alta',
  },
  {
    id: 'pastor',
    name: 'PASTOR',
    category: 'formulas',
    origin: 'Ray Edwards',
    emoji: '✝️',
    description: 'Problema → Amplificación → Historia → Transformación → Oferta → Respuesta. La fórmula más completa para artículos que convierten.',
    howTo: '1. PROBLEMA: Define claramente. 2. AMPLIFICA: Exagera las consecuencias. 3. STORY: Cuéntalo en primera persona. 4. TRANSFORMACIÓN: El antes/después. 5. OFERTA: Tu solución. 6. RESPUESTA: Solicita la acción.',
    example: 'Un artículo completo de 2.000 palabras siguiendo cada paso: problema del blogger → qué pasa si no lo resuelve → tu historia personal → cómo lo superaste → la herramienta que usaste → regístrate aquí.',
    bestFor: ['artículos largos', 'páginas de venta', 'emails de lanzamiento'],
    power: 'muy alta',
  },
  {
    id: '4ps',
    name: '4Ps (Promise-Picture-Proof-Push)',
    category: 'formulas',
    origin: 'Henry Hoke Sr.',
    emoji: '🏆',
    description: 'Promesa → Imagen → Prueba → Empuje. Cuatro elementos que construyen deseo y credibilidad antes de pedir la acción.',
    howTo: '1. PROMISE: Haz una promesa específica. 2. PICTURE: Pinta el escenario deseado. 3. PROOF: Datos, testimoniales, casos. 4. PUSH: Urgencia para actuar ahora.',
    example: '**Promesa:** "Duplica tu tráfico en 90 días." **Imagen:** Cada mañana abrirás tu Analytics y verás cómo el número sube. **Prueba:** 1.247 bloggers ya lo lograron. **Push:** La oferta cierra el domingo.',
    bestFor: ['artículos de lanzamiento', 'emails promocionales'],
    power: 'muy alta',
  },
  {
    id: 'acca',
    name: 'ACCA',
    category: 'formulas',
    origin: 'Institute of Practitioners in Advertising',
    emoji: '🎪',
    description: 'Awareness → Comprensión → Convicción → Acción. Para audiencias que no saben que tienen el problema.',
    howTo: '1. Hazles conscientes del problema. 2. Explica por qué importa. 3. Convéncelos de que tu solución funciona. 4. Pide la acción.',
    example: 'Artículo: "Por qué tu blog no aparece en Google" → Explicas el SEO → Casos de éxito → Descarga la guía.',
    bestFor: ['audiencias frías', 'artículos educativos', 'contenido top-of-funnel'],
    power: 'alta',
  },
  {
    id: 'quest',
    name: 'QUEST',
    category: 'formulas',
    origin: 'Michael Fortin',
    emoji: '⚔️',
    description: 'Qualify → Understand → Educate → Stimulate → Transition. Califica al lector ideal desde el inicio y lo lleva paso a paso.',
    howTo: '1. QUALIFY: "Esto es para ti si..." 2. UNDERSTAND: Muestra que entiendes su dolor. 3. EDUCATE: Enseña algo valioso. 4. STIMULATE: Despierta el deseo. 5. TRANSITION: Llévalo a la siguiente etapa.',
    example: 'Intro: "Si tienes un blog con menos de 1.000 visitas/mes, esto cambiará tu estrategia para siempre..." → comprensión → lección → deseo → CTA.',
    bestFor: ['artículos de lead magnet', 'secuencias de email'],
    power: 'alta',
  },
  {
    id: '4u',
    name: '4U Formula',
    category: 'formulas',
    origin: 'Michael Masterson',
    emoji: '🎯',
    description: 'Urgent + Unique + Ultra-specific + Useful. El framework para titulares y correos que se abren. Cada elemento multiplica el poder del anterior.',
    howTo: 'Puntúa tu titular del 1-4 en cada U. Si sumas menos de 12, reescríbelo. La U más difícil de lograr es Urgent — añade un deadline real o consecuencia.',
    example: '❌ "Consejos de SEO" → ✅ "Los 7 errores de SEO que destruyeron mi tráfico en 30 días (y cómo los evité antes de perder $3.000/mes)"',
    bestFor: ['titulares', 'subjects de email', 'títulos de YouTube'],
    power: 'legendaria',
  },
  {
    id: 'open-loop',
    name: 'Open Loop (Bucle Abierto)',
    category: 'formulas',
    origin: 'Psicología cognitiva / TV serials',
    emoji: '🔄',
    description: 'Abres una pregunta o historia al inicio sin resolverla. El cerebro no puede descansar hasta cerrar el bucle — eso mantiene al lector hasta el final.',
    howTo: 'Abre el artículo con una afirmación que genere una pregunta implícita: "Lo que descubrí ese martes cambió mi negocio para siempre..." → cuenta el contexto primero → resuelve al final.',
    example: '"En 2022 perdí el 80% de mi tráfico de un día para otro. Hoy te cuento exactamente por qué — y lo que ningún guru de SEO menciona." (La respuesta viene 1.500 palabras después.)',
    bestFor: ['intros de artículo', 'threads de Twitter', 'newsletters'],
    power: 'legendaria',
  },
  {
    id: 'slippery-slope',
    name: 'Slippery Slope',
    category: 'formulas',
    origin: 'Joseph Sugarman',
    emoji: '🎿',
    description: 'Cada oración arrastra al lector a leer la siguiente. Como un tobogán — una vez que empieza, no puede parar. El secreto de los artículos que se leen completos.',
    howTo: 'Cada párrafo termina con un gancho que introduce el siguiente. Usa "pero hay un problema...", "aquí viene lo interesante...", "y entonces descubrí algo inesperado..."',
    example: '"El primer paso es simple. → Pero el segundo paso es donde el 90% falla. → La razón es sorprendente. → Resulta que..."',
    bestFor: ['artículos largos', 'newsletters', 'guías paso a paso'],
    power: 'muy alta',
  },
  {
    id: 'bucket-brigade',
    name: 'Bucket Brigade',
    category: 'formulas',
    origin: 'Gary Halbert',
    emoji: '🪣',
    description: 'Frases cortas de transición que mantienen la atención. Palabras como "Escucha:", "Aquí está la cosa:", "¿Y la mejor parte?" que pasan el interés como una cadena de cubos de agua.',
    howTo: 'Inserta estas frases cada 150-200 palabras: "Esto es lo que nadie dice...", "Pero espera...", "Aquí se pone interesante...", "¿Y sabes qué?", "La clave es esta:"',
    example: 'Texto normal → "Pero aquí está el giro..." → nuevo punto → "¿Y lo mejor de todo?" → beneficio → "Esto es lo que cambia todo:" → conclusión.',
    bestFor: ['artículos de blog', 'emails', 'guiones de video'],
    power: 'muy alta',
  },

  // ────────────────── STORYTELLING ──────────────────
  {
    id: 'heros-journey',
    name: "El Viaje del Héroe",
    category: 'storytelling',
    origin: 'Joseph Campbell, 1949',
    emoji: '⚔️',
    description: 'El framework narrativo más poderoso de la historia humana. 12 etapas que se repiten en todos los mitos, películas y marcas exitosas. Tu lector es el héroe — tú eres el mentor.',
    howTo: 'Mundo ordinario → Llamada a la aventura → Rechazo → Mentor → Cruce del umbral → Pruebas → Crisis → Transformación → Regreso con el elixir.',
    example: '"Yo era un blogger ordinario (mundo ordinario). Un día vi que podía vivir de mi blog (llamada). Me daba miedo fallar (rechazo). Encontré a mi mentor (mentor). Empecé a publicar en serio (umbral). Meses de fracasos (pruebas). Casi abandono (crisis). Cambié de estrategia (transformación). Hoy tengo 50.000 suscriptores (regreso)."',
    bestFor: ['artículos de marca personal', 'casos de éxito', 'artículos de origen'],
    power: 'legendaria',
  },
  {
    id: 'story-brand',
    name: 'StoryBrand Framework',
    category: 'storytelling',
    origin: 'Donald Miller',
    emoji: '🌟',
    description: 'El lector es el héroe, tú eres el guía. 7 elementos que clarifican tu mensaje y conectan emocionalmente. Usado por miles de marcas para simplificar comunicaciones complejas.',
    howTo: 'El héroe (lector) tiene un PROBLEMA (villano). Encuentra una GUÍA (tú) que entiende su problema. La guía tiene un PLAN. El héroe toma ACCIÓN. Evita el FRACASO. Logra el ÉXITO.',
    example: 'Tu blog = el héroe. Falta de tráfico = el villano. BlogOS = el guía. Metodología = el plan. Publicar consistente = la acción. Blog muerto = el fracaso evitado. 10K visitas = el éxito.',
    bestFor: ['landing pages', 'artículos de marca', 'páginas "sobre mí"'],
    power: 'legendaria',
  },
  {
    id: 'pixar-spine',
    name: 'Pixar Story Spine',
    category: 'storytelling',
    origin: 'Pixar Animation Studios',
    emoji: '🎬',
    description: 'La estructura narrativa que usa Pixar para todas sus películas: Había una vez... Cada día... Hasta que un día... Por eso... Hasta que finalmente... Y desde entonces...',
    howTo: 'Completa cada frase con tu historia: "Había una vez un blogger que... Cada día publicaba sin ver resultados... Hasta que un día descubrió... Por eso cambió su estrategia... Hasta que finalmente logró... Y desde entonces..."',
    example: '"Había una vez una agencia de marketing en CDMX. Cada día publicaba contenido sin ver engagement. Hasta que un día encontraron los Topic Clusters. Por eso reorganizaron todo su blog. Hasta que finalmente dominaron 3 nichos. Y desde entonces generan el 60% de sus leads desde Google."',
    bestFor: ['estudios de caso', 'testimoniales', 'artículos de transformación'],
    power: 'muy alta',
  },
  {
    id: 'dan-harmon-circle',
    name: 'Círculo de Dan Harmon',
    category: 'storytelling',
    origin: 'Dan Harmon (Community, Rick & Morty)',
    emoji: '🔵',
    description: '8 pasos en círculo: You, Need, Go, Search, Find, Take, Return, Change. El personaje vuelve al punto de partida pero transformado. Crea resonancia emocional profunda.',
    howTo: 'You (el blogger) → Need (necesita tráfico) → Go (busca estrategias) → Search (prueba cosas) → Find (descubre el método) → Take (lo implementa a pesar del miedo) → Return (vuelve a su blog) → Change (ahora tiene 10K/mes).',
    example: 'Artículo: "Cómo pasé de 0 a 10.000 visitantes sin gastar en publicidad" — siguiendo cada etapa del círculo con honestidad.',
    bestFor: ['artículos personales', 'casos de estudio', 'newsletters'],
    power: 'muy alta',
  },
  {
    id: 'in-medias-res',
    name: 'In Medias Res',
    category: 'storytelling',
    origin: 'Horacio, 65 a.C.',
    emoji: '⚡',
    description: 'Empieza en el medio de la acción. El lector llega al artículo en el momento más tenso o emocionante — sin contexto. El contexto llega después. Técnica usada por Homero en La Odisea.',
    howTo: 'Comienza con la escena más dramática de tu historia. "Eran las 3 AM y mi blog acababa de perder el 90% del tráfico." Luego retrocede para explicar cómo llegaste ahí.',
    example: '"Abro mi laptop un lunes y veo el número: $0. Después de 2 años de trabajo. ¿Cómo llegué aquí? Todo empezó 18 meses antes, cuando decidí..." (ahora cuento desde el principio)',
    bestFor: ['artículos de experiencia personal', 'intros impactantes'],
    power: 'muy alta',
  },
  {
    id: 'epiphany-bridge',
    name: 'Epiphany Bridge',
    category: 'storytelling',
    origin: 'Russell Brunson',
    emoji: '💡',
    description: 'Cuenta la historia del momento exacto en que tuviste la revelación. Recrea la misma experiencia emocional en el lector para que llegue a la misma conclusión que tú.',
    howTo: '1. Cuéntalo en primera persona. 2. Describe dónde estabas y cómo te sentías. 3. Narra el momento preciso del "click" mental. 4. Explica cómo cambió todo a partir de ahí.',
    example: '"Estaba en una cafetería en Bogotá revisando mis stats. 47 visitas en todo el mes. Y de repente vi un artículo de la competencia con 120.000 visitas. Abrí el artículo y entendí en 10 segundos por qué mi contenido fallaba. Era el gancho."',
    bestFor: ['artículos de conversión', 'webinars', 'newsletters'],
    power: 'legendaria',
  },
  {
    id: 'three-act',
    name: 'Estructura de 3 Actos',
    category: 'storytelling',
    origin: 'Aristóteles — Poética',
    emoji: '🎭',
    description: 'Setup → Confrontación → Resolución. La estructura narrativa más antigua y universal. El 90% de las películas y los mejores artículos de blog la siguen.',
    howTo: 'Acto 1 (25%): Presenta el mundo y el problema. Acto 2 (50%): El conflicto se intensifica, fracasos, aprendizajes. Acto 3 (25%): La solución y la transformación.',
    example: 'Act 1: "Mi blog fracasó 3 veces." Act 2: "Lo que intenté y por qué no funcionó." Act 3: "El cambio que lo hizo todo diferente — y cómo replicarlo."',
    bestFor: ['artículos largos', 'guías completas', 'historias de marca'],
    power: 'muy alta',
  },
  {
    id: 'kishotenketsu',
    name: 'Kishōtenketsu',
    category: 'storytelling',
    origin: 'Narrativa clásica china/japonesa',
    emoji: '🌸',
    description: 'Ki (introducción) → Shō (desarrollo) → Ten (giro inesperado) → Ketsu (conclusión). Sin conflicto central. El giro crea el interés. Usado en manga, haiku y artículos virales.',
    howTo: 'Introduce un tema → Desarróllalo → Introduce un elemento completamente inesperado → Conecta todo de forma sorprendente.',
    example: 'Intro: Hablar de SEO técnico. Desarrollo: Estrategias de keywords. TEN (giro): "Pero el blog que más crece este año no usa ninguna de estas técnicas..." Ketsu: La lección unificadora.',
    bestFor: ['artículos virales', 'threads de Twitter', 'contenido educativo'],
    power: 'muy alta',
  },
  {
    id: 'freytag',
    name: 'Pirámide de Freytag',
    category: 'storytelling',
    origin: 'Gustav Freytag, 1863',
    emoji: '🔺',
    description: '5 actos: Exposición → Acción ascendente → Clímax → Acción descendente → Desenlace. La estructura clásica del drama que mantiene tensión durante todo el artículo.',
    howTo: 'Exposición (contexto) → Complicaciones crecientes → El momento de mayor tensión → Cómo se resuelve → El nuevo estado del mundo.',
    example: 'Artículo sobre recuperar un blog penalizado: contexto → cada actualización de Google que lo hunde más → el momento de "o lo arreglo o cierro" → las acciones tomadas → el blog recovered.',
    bestFor: ['artículos de superación', 'casos de estudio dramáticos'],
    power: 'alta',
  },
  {
    id: 'origin-story',
    name: 'La Historia de Origen',
    category: 'storytelling',
    origin: 'Psicología de marca',
    emoji: '🌱',
    description: 'El "por qué" de tu blog. La historia que crea conexión emocional profunda y diferencia a los bloggers que construyen comunidades de los que solo acumulan lectores.',
    howTo: '1. El momento de "quebrar" (antes). 2. El catalizador que lo cambió todo. 3. La misión que nació de esa experiencia. 4. Por qué eso beneficia al lector.',
    example: '"Perdí mi trabajo en 2020. Con dos hijos y una hipoteca, empecé un blog sobre finanzas personales desde mi garaje. 18 meses después, ese blog reemplazó mi sueldo. Ahora enseño exactamente cómo lo hice."',
    bestFor: ['página "Sobre mí"', 'artículo de bienvenida', 'presentaciones'],
    power: 'legendaria',
  },
  {
    id: 'nested-story',
    name: 'Historia Dentro de Historia',
    category: 'storytelling',
    origin: 'Las Mil y Una Noches',
    emoji: '🪆',
    description: 'Embeds una historia dentro de otra para crear múltiples niveles de engagement. Cada historia ilustra un punto del artículo de forma que el lector no puede dejar de leer.',
    howTo: 'Historia principal (marco) → Historia secundaria (ilustración de un punto) → Vuelves a la historia principal → Nueva historia secundaria. Las Mil y Una Noches vivía de esto.',
    example: 'Artículo sobre productividad: tu historia de burnout (marco) → la historia de Steve Jobs sobre el punto de quiebre (ilustración) → cómo eso se conecta con tu lección (cierre).',
    bestFor: ['artículos de liderazgo', 'contenido educativo profundo'],
    power: 'alta',
  },
  {
    id: 'transformation-story',
    name: 'La Historia de Transformación',
    category: 'storytelling',
    origin: 'Marketing narrativo moderno',
    emoji: '🦋',
    description: 'Antes (persona en el problema) → Catalizador → Proceso → Después (persona transformada). La fórmula de los testimoniales más efectivos del mundo.',
    howTo: '1. Describe el antes con máximo detalle y empatía. 2. Nombra el catalizador específico. 3. Explica el proceso honestamente. 4. Pinta el después de forma tangible.',
    example: '"María tenía un blog con 0 ingresos y quería cerrar (antes). Un día implementó los Topic Clusters (catalizador). 3 meses de trabajo constante (proceso). Hoy factura $4.500/mes desde su blog (después)."',
    bestFor: ['testimoniales', 'casos de estudio', 'artículos de autoridad'],
    power: 'muy alta',
  },

  // ────────────────── TITULARES ──────────────────
  {
    id: 'numero-titular',
    name: 'El Titular con Número',
    category: 'titulos',
    origin: 'Copywriting digital — David Ogilvy',
    emoji: '🔢',
    description: 'Los números en titulares aumentan el CTR hasta un 36%. El cerebro humano procesa los números más rápido que las palabras y crea expectativas específicas.',
    howTo: 'Usa números impares (7, 11, 13, 21) — son más llamativos. Específicos > redondos (47 > 50). Negros > romanos. Colócalo al inicio o cerca del inicio.',
    example: '❌ "Varias formas de mejorar tu blog" → ✅ "17 técnicas para triplicar el tráfico de tu blog en 90 días"',
    bestFor: ['listicles', 'guías', 'posts de recursos'],
    power: 'muy alta',
  },
  {
    id: 'how-to',
    name: 'El "Cómo..." (How-To)',
    category: 'titulos',
    origin: 'Copywriting clásico',
    emoji: '🛠️',
    description: 'El titular que promete instrucciones prácticas. Hace más de 60 años que "How to..." es el patrón de titular más efectivo en inglés — en español "Cómo..." tiene el mismo poder.',
    howTo: 'Estructura: Cómo [lograr X] [sin Y / en Z tiempo / aunque seas principiante]. Añade especificidad: "Cómo conseguir 1.000 suscriptores sin tener lista de emails ni publicidad.",',
    example: '"Cómo escribir un artículo viral sin experiencia previa" → "Cómo conseguir tus primeros 10.000 seguidores en LinkedIn trabajando solo 30 minutos al día"',
    bestFor: ['tutoriales', 'guías prácticas', 'artículos de resultados'],
    power: 'legendaria',
  },
  {
    id: 'pregunta-titular',
    name: 'El Titular Pregunta',
    category: 'titulos',
    origin: 'Psicología cognitiva',
    emoji: '❓',
    description: 'Las preguntas activan el "Efecto Zeigarnik" — el cerebro queda en bucle abierto hasta obtener la respuesta. El lector no puede ignorar una pregunta bien formulada.',
    howTo: '2 tipos: (1) Pregunta que el lector ya se hace: "¿Por qué nadie lee tu blog?" (2) Pregunta retórica con respuesta implícita: "¿Sabías que el 95% del tráfico va al #1 en Google?"',
    example: '"¿Por qué algunos blogs generan $10.000/mes y el tuyo no?" | "¿Cuál es el error de SEO que comete el 87% de los bloggers?"',
    bestFor: ['artículos de problema', 'contenido educativo', 'debates'],
    power: 'muy alta',
  },
  {
    id: 'secreto-titular',
    name: 'El Titular "Lo que nadie dice"',
    category: 'titulos',
    origin: 'Tabloids y prensa amarilla → Blogs',
    emoji: '🤫',
    description: 'Activa el FOMO y la curiosidad de "información exclusiva". El cerebro está cableado para valorar lo que parece escaso o prohibido.',
    howTo: 'Variaciones: "Lo que nadie te dice sobre X", "El secreto que los expertos ocultan", "La verdad sobre X", "Lo que descubrí después de X años".',
    example: '"Lo que nadie dice sobre el SEO en 2024" | "El secreto que los grandes bloggers no enseñan en sus cursos" | "La verdad incómoda sobre monetizar un blog"',
    bestFor: ['artículos de opinión', 'contenido de autoridad', 'análisis'],
    power: 'muy alta',
  },
  {
    id: 'advertencia-titular',
    name: 'El Titular de Advertencia',
    category: 'titulos',
    origin: 'Copywriting de respuesta directa',
    emoji: '⚠️',
    description: 'La aversión a la pérdida es 2x más poderosa que el deseo de ganancia (Kahneman). Los titulares de advertencia explotan este sesgo cognitivo universal.',
    howTo: '"Cuidado con X", "Nunca hagas X", "El error que destruye X", "Para antes de X". Específico es más poderoso que genérico.',
    example: '"Nunca publiques en tu blog sin hacer esto primero" | "El error de SEO que destruyó mi tráfico en 48 horas" | "Para antes de comprar un curso de blogging"',
    bestFor: ['artículos de errores comunes', 'contenido preventivo'],
    power: 'muy alta',
  },
  {
    id: 'contrarian-titular',
    name: 'El Titular Contrario',
    category: 'titulos',
    origin: 'Periodismo de opinión',
    emoji: '🔄',
    description: 'Contradice la sabiduría convencional. Los lectores son adictos a las perspectivas que los sorprenden. El cerebro se activa ante lo inesperado.',
    howTo: 'Toma el consejo más común de tu nicho y contradicelo con datos o argumento sólido: "Por qué NO deberías [consejo popular]".',
    example: '"Por qué publicar menos artículos dispara tu tráfico" | "El SEO está sobrevalorado — esto es lo que realmente funciona" | "Deja de construir tu lista de emails"',
    bestFor: ['artículos de opinión', 'contenido viral', 'análisis'],
    power: 'muy alta',
  },
  {
    id: 'guia-definitiva',
    name: 'La Guía Definitiva / Completa',
    category: 'titulos',
    origin: 'Content marketing moderno',
    emoji: '📚',
    description: 'El formato "Guía definitiva" posiciona al artículo como la fuente más completa del tema — atrae backlinks, rankea para múltiples keywords y establece autoridad de dominio.',
    howTo: 'El artículo DEBE ser extraordinariamente completo (2.000-8.000 palabras). Incluye tabla de contenidos, múltiples secciones, ejemplos, datos, recursos.',
    example: '"La Guía Definitiva de Content Marketing 2024" | "Todo lo que necesitas saber sobre SEO para bloggers" | "La Guía Completa para Monetizar tu Blog desde Cero"',
    bestFor: ['pillar content', 'artículos de autoridad', 'lead magnets'],
    power: 'legendaria',
  },
  {
    id: 'vs-titular',
    name: 'El Titular VS',
    category: 'titulos',
    origin: 'Marketing comparativo',
    emoji: '⚡',
    description: 'Comparaciones explícitas generan clicks porque el lector ya tiene una opinión y quiere ver si tiene razón. También son altamente buscadas en Google.',
    howTo: 'X vs Y: puede ser herramientas, estrategias, estilos, o incluso tiempo ("SEO vs Publicidad pagada: cuál es mejor para bloggers nuevos").',
    example: '"WordPress vs Substack: ¿Cuál deberías usar en 2024?" | "SEO vs Redes Sociales: Cuál genera más tráfico gratuito" | "Blog vs YouTube: Cuál monetiza más rápido"',
    bestFor: ['artículos comparativos', 'reviews', 'ayuda en decisiones'],
    power: 'muy alta',
  },
  {
    id: 'caso-estudio-titular',
    name: 'El Titular de Caso Real',
    category: 'titulos',
    origin: 'Harvard Business School → Blogging',
    emoji: '📊',
    description: 'Los casos reales con números específicos son los más compartidos. La especificidad ("pasé de 200 a 15.000 visitas") genera credibilidad inmediata.',
    howTo: 'Incluye: un nombre o referencia real, métricas específicas, timeframe. "Cómo [persona] logró [resultado específico] en [tiempo] usando [método]."',
    example: '"Cómo este blogger de Ciudad de México pasó de $0 a $8.000/mes en 14 meses" | "El artículo de 3.000 palabras que me trajo 1.2M de visitas"',
    bestFor: ['artículos de autoridad', 'contenido de prueba social'],
    power: 'muy alta',
  },
  {
    id: 'year-titular',
    name: 'El Titular con Año',
    category: 'titulos',
    origin: 'SEO content marketing',
    emoji: '📅',
    description: 'Agregar el año actual señaliza que el contenido está actualizado — el lector y Google lo prefieren sobre contenido sin fecha. Aumenta el CTR orgánico en 10-30%.',
    howTo: 'Agrega "(2024)" o "en 2024" al titular. Actualiza el año cada enero para mantener el artículo relevante.',
    example: '"Las 15 mejores herramientas de SEO en 2024" | "Cómo empezar un blog exitoso en 2024: guía completa" | "Monetización de blogs 2024: lo que funciona ahora"',
    bestFor: ['artículos evergreen', 'comparativas', 'listas de recursos'],
    power: 'alta',
  },

  // ────────────────── PERSUASIÓN ──────────────────
  {
    id: 'social-proof',
    name: 'Prueba Social',
    category: 'persuasion',
    origin: 'Robert Cialdini — Influencia (1984)',
    emoji: '👥',
    description: 'Las personas miran a otros para decidir qué hacer. El primer principio de influencia de Cialdini. Testimoniales, números, menciones y endorsements activan este sesgo.',
    howTo: 'Tipos: números ("más de 50.000 bloggers"), testimoniales específicos, logos de medios, menciones de expertos, casos de éxito con nombres reales.',
    example: '"Más de 12.400 bloggers ya usan este método" | Testimonial de alguien con nombre, cargo y resultado específico | Logos de medios donde apareciste.',
    bestFor: ['landing pages', 'artículos de credibilidad', 'páginas de venta'],
    power: 'legendaria',
  },
  {
    id: 'escasez',
    name: 'Escasez y Urgencia',
    category: 'persuasion',
    origin: 'Robert Cialdini — Influencia (1984)',
    emoji: '⏳',
    description: 'Lo escaso parece más valioso. Lo urgente genera acción inmediata. El cerebro humano está programado para reaccionar al peligro de perder oportunidades.',
    howTo: 'Escasez real: plazas limitadas, edición limitada. Urgencia real: deadlines con razón lógica. NUNCA artificial — destruye la confianza cuando se descubre.',
    example: '"Solo 47 lugares disponibles para el próximo batch" | "Esta guía se elimina el viernes porque lanzamos la versión 2.0"',
    bestFor: ['CTAs', 'lanzamientos', 'ofertas con deadline'],
    power: 'muy alta',
  },
  {
    id: 'autoridad',
    name: 'Posicionamiento de Autoridad',
    category: 'persuasion',
    origin: 'Robert Cialdini — Influencia (1984)',
    emoji: '🏅',
    description: 'Seguimos a los expertos. La autoridad puede ser credencial, experiencia, logros medibles o asociación. Establécela en los primeros 100 palabras.',
    howTo: 'Menciona: años de experiencia, resultados específicos logrados, publicaciones en medios reconocidos, resultados de otros. Muestra, no proclames.',
    example: '"Después de analizar 847 blogs que alcanzaron 100.000 visitas/mes..." | "Como blogger que ha generado más de $1M en ingresos digitales..."',
    bestFor: ['artículos técnicos', 'tutoriales avanzados', 'contenido pago'],
    power: 'muy alta',
  },
  {
    id: 'reciprocidad',
    name: 'Reciprocidad',
    category: 'persuasion',
    origin: 'Robert Cialdini — Influencia (1984)',
    emoji: '🎁',
    description: 'Cuando das algo valioso gratis, el lector siente una deuda psicológica de correspondencia. La base de todo content marketing efectivo.',
    howTo: 'Da ANTES de pedir. El lead magnet, el artículo ultra-completo, el template descargable — todos activan reciprocidad. El valor del regalo debe superar lo que pides a cambio.',
    example: 'Un artículo de 5.000 palabras con todo el conocimiento real → al final, un CTA pequeño. La relación es: 95% valor / 5% petición.',
    bestFor: ['lead magnets', 'artículos gratuitos completos', 'email marketing'],
    power: 'legendaria',
  },
  {
    id: 'anchoring',
    name: 'El Efecto de Anclaje',
    category: 'persuasion',
    origin: 'Amos Tversky y Daniel Kahneman, 1974',
    emoji: '⚓',
    description: 'El primer número o idea que el lector ve ancla su percepción de todo lo que viene después. Usado en precios, estadísticas y comparaciones.',
    howTo: 'Presenta primero el número grande o el contraste extremo. "Otros cobran $2.000 por esta información. Aquí la tienes gratis." El valor percibido de tu contenido sube automáticamente.',
    example: '"La agencia de SEO te cobró $3.000 al mes por esto. Hoy te enseño a hacerlo tú mismo en 2 horas." | "Este método generó $847.000 para una sola empresa. Tú puedes empezar con $0."',
    bestFor: ['artículos de valor', 'páginas de precio', 'comparativas'],
    power: 'muy alta',
  },
  {
    id: 'cognitive-dissonance',
    name: 'Disonancia Cognitiva',
    category: 'persuasion',
    origin: 'Leon Festinger, 1957',
    emoji: '🌀',
    description: 'El lector no puede creer X y hacer lo opuesto de X. Si logras que el lector acepte una premisa, su mente exigirá comportarse de acuerdo a ella.',
    howTo: 'Primero haz que el lector acepte una verdad ("el contenido de calidad es el único que funciona"). Luego conecta esa verdad con tu CTA ("entonces necesitas esta metodología").',
    example: '"Tú ya sabes que el contenido mediocre no funciona. Si sigues publicando sin estrategia, seguirás teniendo los mismos resultados. La pregunta es: ¿qué vas a hacer diferente?"',
    bestFor: ['artículos de conversión', 'emails de seguimiento'],
    power: 'muy alta',
  },
  {
    id: 'pattern-interrupt',
    name: 'Pattern Interrupt',
    category: 'persuasion',
    origin: 'Programación Neurolingüística (PNL)',
    emoji: '🔔',
    description: 'El cerebro filtra el 99% del contenido que procesa. Para ser leído, primero tienes que romper el patrón. Una frase inesperada, un número sorprendente o un visual disruptivo logran esto.',
    howTo: 'Inicio inesperado: "No voy a darte otro artículo genérico de SEO." | Dato contradictorio al inicio. | Una declaración que va contra lo que el lector espera.',
    example: '"Este artículo va a destruir el 80% de lo que crees saber sobre content marketing." | "Llevo 5 años diciendo que el SEO es lo más importante. Estaba equivocado."',
    bestFor: ['intros de artículo', 'subjects de email', 'publicaciones sociales'],
    power: 'legendaria',
  },
  {
    id: 'zeigarnik',
    name: 'Efecto Zeigarnik',
    category: 'persuasion',
    origin: 'Bluma Zeigarnik, 1927',
    emoji: '🔓',
    description: 'Las tareas incompletas permanecen activas en la memoria. Una historia sin terminar, una pregunta sin responder o una serie incompleta generan obsesión por el cierre.',
    howTo: 'Crea múltiples bucles abiertos en el artículo. Anuncia que algo viene ("más adelante en este artículo verás el error #1 que...") y luego entrega.',
    example: '"Hay un error que cometen el 90% de los bloggers y que mencionaré al final de este artículo. Guarda eso en mente mientras lees..."',
    bestFor: ['artículos seriales', 'newsletters', 'threads de Twitter'],
    power: 'muy alta',
  },
  {
    id: 'future-pacing',
    name: 'Future Pacing',
    category: 'persuasion',
    origin: 'Hipnosis ericksoniana / PNL',
    emoji: '🔮',
    description: 'Lleva al lector mentalmente al futuro donde ya logró el resultado. Crea un estado emocional positivo asociado a tu contenido/producto antes de presentarlo.',
    howTo: 'Usa tiempo presente futuro: "Imagina que son las 9 AM del martes. Abres tu laptop. Ves 847 nuevas visitas. El artículo que escribiste la semana pasada está rankeando #1."',
    example: '"Visualiza este momento: son las 10 AM, ya publicaste tu artículo de la semana, tu lista creció 300 personas y tienes 2 consultas de potenciales clientes en tu inbox."',
    bestFor: ['artículos de ventas', 'intros de newsletter', 'CTAs'],
    power: 'muy alta',
  },
  {
    id: 'ben-franklin',
    name: 'El Efecto Ben Franklin',
    category: 'persuasion',
    origin: 'Benjamin Franklin (autobiografía)',
    emoji: '🔑',
    description: 'Pedirle un pequeño favor al lector crea simpatía hacia tu contenido. Al actuar en favor de algo, el cerebro racionaliza que le gusta. Aplicado al engagement en blogs.',
    howTo: 'Pide acciones pequeñas primero: "Guarda este artículo", "Marca este punto como favorito", "Escríbeme una palabra en comentarios". Luego pide el compromiso mayor.',
    example: '"Antes de seguir: ¿puedes subrayar la frase más útil para ti de este artículo? (Yo espero.) (...) Ahora sigamos."',
    bestFor: ['artículos interactivos', 'newsletters', 'cursos escritos'],
    power: 'alta',
  },

  // ────────────────── GATILLOS EMOCIONALES ──────────────────
  {
    id: 'fear-fomo',
    name: 'FOMO (Fear Of Missing Out)',
    category: 'emocional',
    origin: 'Psicología social moderna',
    emoji: '😰',
    description: 'El miedo a quedarse fuera es uno de los motivadores más poderosos de acción. El 69% de los millennials reportan experimentar FOMO regularmente. Usa con responsabilidad.',
    howTo: 'Muestra lo que otros ya están logrando. Presenta la oportunidad como limitada en tiempo o acceso. La clave es que el resultado deseado sea real y alcanzable.',
    example: '"Mientras lees esto, hay bloggers en tu nicho posicionando exactamente las keywords que tú deberías estar atacando. El tráfico que van a recibir era tuyo."',
    bestFor: ['artículos de urgencia', 'CTAs', 'lanzamientos'],
    power: 'muy alta',
  },
  {
    id: 'curiosity-gap',
    name: 'El Curiosity Gap',
    category: 'emocional',
    origin: 'George Loewenstein, Carnegie Mellon',
    emoji: '🤔',
    description: 'La mente humana odia los espacios de información incompleta. El Curiosity Gap es la distancia entre lo que el lector sabe y lo que quiere saber. Tu titular y primer párrafo deben abrirlo.',
    howTo: 'Técnica: revela parcialmente algo sorprendente sin dar la respuesta completa. "Hay un error que cometen hasta los bloggers avanzados que destruye su SEO. Y no, no es lo que crees."',
    example: 'BuzzFeed construyó un imperio con esta técnica: "Lo que descubrió este blogger cambió para siempre la forma en que todos escribimos intros." (¿Qué fue? El lector DEBE saberlo.)',
    bestFor: ['titulares', 'intros', 'thumbnails', 'subjects de email'],
    power: 'legendaria',
  },
  {
    id: 'identidad',
    name: 'Apelación a la Identidad',
    category: 'emocional',
    origin: 'Psicología social — Self-Concept Theory',
    emoji: '👤',
    description: 'Las personas actúan consistentemente con cómo se definen a sí mismas. Si logras que el lector se identifique como "un blogger serio", actuará como tal.',
    howTo: 'Usa "Los bloggers serios hacen X", "Si eres del tipo de persona que...", "Como alguien que se toma su blog en serio, seguramente ya sabes..."',
    example: '"Los bloggers que van a sobrevivir en 2024 son los que hoy están invirtiendo en estrategia. Si estás leyendo esto, probablemente eres uno de ellos."',
    bestFor: ['artículos de comunidad', 'newsletters', 'apertura de email'],
    power: 'muy alta',
  },
  {
    id: 'empatia-radical',
    name: 'Empatía Radical',
    category: 'emocional',
    origin: 'Psicología clínica / Brené Brown',
    emoji: '❤️',
    description: 'Hacer que el lector sienta "este artículo fue escrito para MÍ". La empatía radical es nombrar exactamente el pensamiento o sentimiento que tiene el lector en este momento.',
    howTo: 'Investigación profunda del lector: ¿qué dice en foros, comentarios, grupos? Usa sus palabras exactas. La precisión del dolor genera confianza automática.',
    example: '"Sé exactamente lo que sientes. Llevas semanas publicando, esforzándote, y el número de visitas sigue siendo el mismo. Y empiezas a preguntarte si tiene sentido continuar."',
    bestFor: ['intros de artículo', 'emails de bienvenida', 'páginas de venta'],
    power: 'legendaria',
  },
  {
    id: 'orgullo',
    name: 'El Apelo al Orgullo',
    category: 'emocional',
    origin: 'Retórica clásica — Aristóteles',
    emoji: '💪',
    description: 'El deseo de ser respetado, admirado y visto como inteligente/exitoso. Posiciona la acción del lector como algo que los distingue de la mayoría mediocre.',
    howTo: 'Frame: "Los que entienden X están un paso adelante". Hacer lo que propones = ser parte de la élite. No hacerlo = quedarse en la mediocridad.',
    example: '"El 95% de los bloggers nunca aplica esto porque requiere disciplina real. Tú no eres del 95%." | "Solo el 1% de los bloggers entiende la importancia de los Topic Clusters."',
    bestFor: ['artículos aspiracionales', 'CTAs de comunidad'],
    power: 'alta',
  },
  {
    id: 'nostalgia',
    name: 'La Técnica de la Nostalgia',
    category: 'emocional',
    origin: 'Psicología del consumidor',
    emoji: '🌅',
    description: 'La nostalgia aumenta el sentido de continuidad personal y la disposición a conectar. Los artículos que evocan un pasado mejor o una referencia compartida generan engagement emocional más profundo.',
    howTo: 'Referencia un tiempo o momento específico que la audiencia comparte. "¿Recuerdas cuando el algoritmo de Google era predecible?" Conecta ese pasado con el presente.',
    example: '"Había un tiempo (antes de 2015) en que publicar 300 palabras y añadir keywords era suficiente para rankear. Ese mundo ya no existe. El nuevo exige algo completamente diferente."',
    bestFor: ['artículos de nicho experto', 'newsletters de comunidad'],
    power: 'alta',
  },
  {
    id: 'surprise-reveal',
    name: 'El Gran Reveal',
    category: 'emocional',
    origin: 'Teatro y cine — "El twist"',
    emoji: '🎭',
    description: 'El giro inesperado en la mitad o el final del artículo que reenmarca todo lo anterior. El lector no puede dejar de compartirlo porque quiere que otros experimenten esa misma sorpresa.',
    howTo: 'Construye expectativas en una dirección → revela que la realidad es completamente diferente. La sorpresa debe ser genuina, no artificial.',
    example: '"Pasé 6 meses creyendo que mi blog fracasaba por falta de SEO. El verdadero problema era algo mucho más simple y devastador: nadie sabía que existía."',
    bestFor: ['artículos virales', 'contenido de opinión', 'newsletters'],
    power: 'muy alta',
  },

  // ────────────────── ESTRUCTURA ──────────────────
  {
    id: 'inverted-pyramid',
    name: 'La Pirámide Invertida',
    category: 'estructura',
    origin: 'Periodismo del siglo XIX',
    emoji: '🔻',
    description: 'Lo más importante primero. Origen: periodistas que enviaban despachos por telégrafo temían que la línea se cortara. Hoy: los lectores se van en los primeros 30 segundos.',
    howTo: 'Párrafo 1: la conclusión completa. Párrafos siguientes: el contexto y detalles. El lector que se va en 30 segundos se lleva el mensaje esencial.',
    example: 'Artículo "Cómo triplicar tu tráfico": Párrafo 1: "Un solo cambio triplicó mi tráfico: pasar de artículos sueltos a Topic Clusters. Aquí exactamente cómo hacerlo." Resto: detalles y casos.',
    bestFor: ['artículos de noticias', 'posts de redes sociales', 'intros de alto impacto'],
    power: 'muy alta',
  },
  {
    id: 'skyscraper',
    name: 'La Técnica del Rascacielos',
    category: 'estructura',
    origin: 'Brian Dean — Backlinko',
    emoji: '🏙️',
    description: 'Encuentra el mejor artículo sobre un tema → crea uno 10x mejor → promociónalo a los que linkearon al original. La técnica de link building más replicable del content marketing.',
    howTo: '1. Busca en Google tu keyword objetivo. 2. Analiza el artículo #1. 3. Escribe uno más completo, actualizado, visual y útil. 4. Contacta a los sites que linkearon al original.',
    example: '"The Ultimate Guide to SEO" de Backlinko: analizó los top resultados para "SEO guide", creó algo 3x más completo, consiguió 8.600 backlinks.',
    bestFor: ['artículos pillar', 'link building', 'contenido de autoridad'],
    power: 'legendaria',
  },
  {
    id: 'topic-cluster',
    name: 'Topic Cluster (Pilar + Satélites)',
    category: 'estructura',
    origin: 'HubSpot — 2017',
    emoji: '🕸️',
    description: 'Un artículo pilar (5.000+ palabras) cubre el tema principal. 8-15 artículos satélite cubren subtemas específicos. El enlazado interno señaliza a Google que eres la autoridad del tema.',
    howTo: '1. Elige 1 tema principal. 2. Identifica 10 subtemas. 3. Escribe el pilar primero. 4. Escribe los satélites enlazando al pilar. 5. Enlaza satélites entre sí cuando es relevante.',
    example: 'Pilar: "Marketing de contenidos para bloggers" → Satélites: "Cómo escribir titulares", "SEO para blogs", "Frecuencia de publicación", "Distribución de contenido", etc.',
    bestFor: ['estrategia SEO a largo plazo', 'autoridad de nicho'],
    power: 'legendaria',
  },
  {
    id: 'faq-structure',
    name: 'Estructura FAQ',
    category: 'estructura',
    origin: 'SEO — Featured Snippets',
    emoji: '❓',
    description: 'Responde las preguntas más buscadas de tu audiencia en formato pregunta-respuesta. Google posiciona el 8% del tráfico en Featured Snippets — el 60% son FAQs.',
    howTo: 'Usa Google Autocomplete, People Also Ask, AnswerThePublic y comentarios de tu audiencia. Cada respuesta: 40-60 palabras (ideal para featured snippet), luego amplía.',
    example: 'Artículo: "Marketing de contenidos: preguntas frecuentes" → 20 preguntas reales que buscan tus lectores, respondidas con precisión y profundidad.',
    bestFor: ['SEO', 'contenido educativo', 'captura de featured snippets'],
    power: 'muy alta',
  },
  {
    id: 'listicle',
    name: 'El Listicle Extendido',
    category: 'estructura',
    origin: 'BuzzFeed → Long-form blogging',
    emoji: '📋',
    description: 'Una lista numerada donde cada ítem es desarrollado con profundidad real. El formato que más se comparte en redes + el que más rankea en Google cuando es completo.',
    howTo: 'Cada ítem necesita: nombre claro → explicación (2-3 párrafos) → ejemplo específico → aplicación práctica. NO es una lista simple de bullets.',
    example: '"23 técnicas de copywriting que usan los mejores bloggers" — cada técnica con descripción completa, ejemplo real y cómo aplicarla. Artículo de 6.000 palabras.',
    bestFor: ['artículos virales', 'recursos', 'comparativas'],
    power: 'muy alta',
  },
  {
    id: 'before-after-case',
    name: 'Estructura Antes/Después',
    category: 'estructura',
    origin: 'Copywriting de respuesta directa',
    emoji: '🔀',
    description: 'Muestra el estado inicial (con datos reales) y el estado final (con datos reales). El contraste visual y numérico hace que los resultados sean visceralmente comprensibles.',
    howTo: 'Tabla, gráfico o sección visual que muestre métricas reales antes y después. "Tráfico antes: 847/mes → después: 47.000/mes" tiene más impacto que cualquier descripción.',
    example: 'Screenshots de Google Analytics antes/después. Ingreso mensual en el mes 1 vs mes 12. Número de suscriptores al inicio vs al año.',
    bestFor: ['casos de estudio', 'testimoniales', 'artículos de resultados'],
    power: 'muy alta',
  },
  {
    id: 'data-story',
    name: 'Data Storytelling',
    category: 'estructura',
    origin: 'Periodismo de datos — Edward Tufte',
    emoji: '📊',
    description: 'Los datos solos son aburridos. Los datos dentro de una narrativa son irresistibles. El arte de usar estadísticas para contar historias que crean cambio.',
    howTo: '1. Dato sorprendente de apertura. 2. Contexto narrativo. 3. Implicaciones personales para el lector. 4. Conclusión accionable. Cada dato necesita los 4 pasos.',
    example: '"El 66% del tráfico de búsqueda va al #1 en Google. (Dato.) Eso significa que el #2 recibe 9 veces menos tráfico que el #1. (Contexto.) Si tu artículo está en posición 4, estás dejando el 90% del tráfico potencial en la mesa. (Implicación.) Aquí está cómo llegar al #1. (Acción.)"',
    bestFor: ['artículos técnicos', 'análisis de industria', 'artículos de autoridad'],
    power: 'muy alta',
  },
  {
    id: 'metaphor',
    name: 'La Metáfora Explicativa',
    category: 'estructura',
    origin: 'Retórica clásica',
    emoji: '🌉',
    description: 'Los conceptos complejos se aprenden más rápido y se recuerdan más tiempo cuando se explican a través de metáforas familiares. El 70% de las conversaciones cotidianas son metáforas.',
    howTo: 'Identifica el concepto complejo → busca un dominio familiar con la misma estructura → úsala consistentemente. No mezcles metáforas en el mismo artículo.',
    example: '"El SEO es como una competición de atletismo. No te importa correr más rápido que Usain Bolt. Solo necesitas correr más rápido que las otras páginas en tu categoría específica."',
    bestFor: ['artículos técnicos', 'tutoriales para principiantes', 'analogías'],
    power: 'muy alta',
  },
  {
    id: 'rule-of-three',
    name: 'La Regla de Tres',
    category: 'estructura',
    origin: 'Retórica latina — Omne trium perfectum',
    emoji: '3️⃣',
    description: 'El cerebro humano encuentra patrones en grupos de tres y los percibe como completos y satisfactorios. Julius Caesar, Steve Jobs y los mejores copywriters lo usan constantemente.',
    howTo: 'Agrupa siempre en 3s: 3 razones, 3 pasos, 3 beneficios, 3 errores. "Veni, vidi, vici." | "Simplicity, simplicity, simplicity." | "3 pasos para..."',
    example: '"Hay 3 razones por las que tu blog no genera tráfico: tu estrategia de keywords, tu frecuencia de publicación y tu red de distribución."',
    bestFor: ['estructura de artículos', 'CTAs', 'presentaciones'],
    power: 'alta',
  },

  // ────────────────── ENGAGEMENT ──────────────────
  {
    id: 'especificidad',
    name: 'El Principio de Especificidad',
    category: 'engagement',
    origin: 'Claude Hopkins — Scientific Advertising (1923)',
    emoji: '🔬',
    description: 'Lo específico vende, lo genérico fracasa. Un número específico tiene más credibilidad que uno redondo. Un resultado concreto mueve más que una promesa vaga.',
    howTo: 'Remplaza: "mucho tráfico" → "47.000 visitas mensuales". "Bastante dinero" → "$8.347 al mes". "Muchos suscriptores" → "12.400 suscriptores activos".',
    example: '❌ "Este artículo generó mucho tráfico" → ✅ "Este artículo generó 1.2M de visitas en 18 meses, 47.000 suscriptores y $340.000 en ventas directas"',
    bestFor: ['titulares', 'testimoniales', 'resultados de casos'],
    power: 'legendaria',
  },
  {
    id: 'voice-of-customer',
    name: 'Voice of Customer (VoC)',
    category: 'engagement',
    origin: 'Marketing de investigación',
    emoji: '🎙️',
    description: 'Usar las palabras exactas que tu audiencia usa para describir su problema. Cuando el lector lee sus propias palabras, siente que el artículo fue escrito solo para él.',
    howTo: 'Minería de datos: lee 100 comentarios de YouTube, reseñas de Amazon, posts de Facebook Groups de tu nicho. Copia las frases recurrentes. Úsalas literalmente en tu copy.',
    example: '"No sé cómo empezar" → usa "no saber por dónde empezar". "Me siento abrumado" → usa "sentirse abrumado". El lector piensa: "¡Exacto! ¡Este blogger me entiende!"',
    bestFor: ['intros de artículo', 'páginas de venta', 'emails'],
    power: 'legendaria',
  },
  {
    id: 'cliffhanger',
    name: 'El Cliffhanger',
    category: 'engagement',
    origin: 'Literatura serializada victoriana — Charles Dickens',
    emoji: '🧗',
    description: 'Termina secciones o artículos en el momento de mayor tensión, obligando al lector a continuar. Dickens lo usó para crear suspenso semana a semana. Netflix lo usa para crear binge-watching.',
    howTo: 'No resuelvas la tensión al final de cada sección. Anuncia el próximo punto más emocionante ANTES de terminar el actual. "Y ahí fue cuando descubrí el error que casi destruye todo. Pero primero..."',
    example: '"Después de implementar esas 3 estrategias, mis resultados mejoraron significativamente. Pero lo que vino después nadie lo esperaba — ni yo. Cuento de ese momento en la siguiente sección."',
    bestFor: ['artículos seriales', 'newsletters', 'artículos largos'],
    power: 'muy alta',
  },
  {
    id: 'micro-story',
    name: 'La Micro-Historia',
    category: 'engagement',
    origin: 'Narrativa flash / Hemingway',
    emoji: '✍️',
    description: 'Una historia completa en 2-5 oraciones. Hemingway escribió: "For sale: baby shoes, never worn." El cerebro completa el resto. Las micro-historias son el engagement más eficiente que existe.',
    howTo: 'Personaje + situación + conflicto + resolución o pregunta abierta, en 4-5 oraciones máximo. Una por punto importante del artículo.',
    example: '"Carlos abrió su laptop a las 6 AM. Revisó las estadísticas de ayer. 0 visitas. 0 suscriptores nuevos. 18 meses de publicar dos veces por semana. Cerró la laptop. Ese fue el día que todo cambió."',
    bestFor: ['intros de artículo', 'transiciones entre secciones', 'testimoniales'],
    power: 'muy alta',
  },
  {
    id: 'callback',
    name: 'El Callback (Conexión Final)',
    category: 'engagement',
    origin: 'Stand-up comedy → Storytelling',
    emoji: '🔁',
    description: 'Regresar al inicio del artículo al final para cerrar el loop narrativo. La sensación de cierre genera satisfacción emocional y hace que el artículo se sienta "completo".',
    howTo: 'En el intro mencionas una historia, pregunta o idea. En el cierre, vuelves a ella y la resuelves o la ves desde una nueva perspectiva. El lector siente la satisfacción del cierre.',
    example: 'Intro: "Esa mañana cuando perdí el 90% de mi tráfico..." → Cierre: "Hoy, mirando hacia atrás a esa mañana de 2022, entiendo que fue el mejor día de mi carrera como blogger. Sin esa crisis, nunca hubiera descubierto el método que cambió todo."',
    bestFor: ['artículos personales', 'newsletters', 'artículos largos'],
    power: 'muy alta',
  },
  {
    id: 'so-what-test',
    name: 'El Test "¿Y qué?"',
    category: 'engagement',
    origin: 'Edición periodística',
    emoji: '🧪',
    description: 'Después de cada párrafo, pregúntate: "¿Y qué? ¿Por qué le importa esto al lector?" Si no tienes una respuesta clara, el párrafo sobra. El artículo más corto que responde todas las preguntas supera al largo que no.',
    howTo: 'Edición: lee cada párrafo y pregunta "¿Y qué le importa esto al lector específico que definí?". Si la respuesta no es obvia, añade la "implicación para ti" o elimina el párrafo.',
    example: '"Google actualizó su algoritmo en marzo de 2024. (¿Y qué?) Esto significa que los artículos que dependían solo de backlinks perdieron posiciones. (¿Y qué para ti?) Si tienes más de 3 artículos en posiciones 4-10, esta estrategia puede llevarlos al top 3 en 60 días."',
    bestFor: ['edición de artículos', 'mejora de artículos existentes'],
    power: 'muy alta',
  },
  {
    id: 'myth-reality',
    name: 'Mito vs Realidad',
    category: 'engagement',
    origin: 'Formato periodístico / Debate',
    emoji: '⚡',
    description: 'Uno de los formatos más compartidos: derrumbar creencias establecidas con evidencia. Activa el instinto de curiosidad y el deseo de parecer informado ante otros.',
    howTo: 'Estructura: "Mito: X es verdad → Realidad: los datos muestran Y." Usa al menos 3-5 pares. Apoya cada realidad con dato, estudio o caso específico.',
    example: '"Mito: publicar más frecuentemente = más tráfico. Realidad: HubSpot estudió 15.000 blogs y descubrió que la calidad predice el tráfico 5x más que la cantidad."',
    bestFor: ['artículos de opinión', 'artículos de investigación', 'contenido viral'],
    power: 'muy alta',
  },
  {
    id: 'you-language',
    name: 'El Lenguaje "Tú"',
    category: 'engagement',
    origin: 'Copywriting directo — Gary Halbert',
    emoji: '👆',
    description: 'La palabra más poderosa del copywriting no es "gratis" ni "nuevo" — es "TÚ". Hablarle directamente al lector crea una conexión uno a uno en un medio de masas.',
    howTo: 'Relación 3:1 → por cada vez que dices "yo", di "tú" tres veces. Revisa todos tus artículos y cuenta: si hay más "yo" que "tú", la proporción está mal.',
    example: '❌ "En este artículo vamos a ver cómo mejorar el SEO" → ✅ "Después de leer esto, tú sabrás exactamente cómo llevar tu blog a posiciones que tu competencia ni imagina."',
    bestFor: ['todos los artículos', 'emails', 'páginas de venta'],
    power: 'legendaria',
  },
  {
    id: 'contrarian-take',
    name: 'La Opinión Contraria',
    category: 'engagement',
    origin: 'Periodismo de opinión / Thought leadership',
    emoji: '🔥',
    description: 'El contenido que desafía el consenso genera el triple de comentarios y compartidos. Los lectores quieren que los hagan pensar diferente — pero solo si el argumento es sólido.',
    howTo: '1. Identifica el consejo más común de tu nicho. 2. Busca evidencia que lo contradiga. 3. Presenta el argumento contrario con datos y lógica sólida. 4. Acepta la complejidad — no todo es binario.',
    example: '"El email marketing está muerto: por qué tu newsletter es el peor uso de tu tiempo en 2024" — con datos reales de tasas de apertura y conversión vs otras estrategias.',
    bestFor: ['artículos virales', 'thought leadership', 'contenido de debate'],
    power: 'muy alta',
  },
]
